In [ ]:
# Importing the Numpy package to generate random integers.
import numpy as np
# Creating a varianble named "random_vec".
# Here I am using random function to generate random integers with a certain range.
# Here my range is 15.
random_vec = np.random.randint(1, 21, size = 15)
# Printing the array
print(random_vec)
print()

# Reshaping the size of Random array to 3 by 5.
# Here we use the Reshape() method to reshape the array.
reshaped_vec = random_vec.reshape(3,5)
print(reshaped_vec)
print()

# Replacing the max value in each row with 0 in the reshaped vector.
reshaped_vec = np.where(reshaped_vec == reshaped_vec.max(axis = 1, keepdims = True), 0, reshaped_vec)
# Printing the reshaped vector with the modified values.
print(reshaped_vec)

[ 2  4  7 10  4 15  2  3 19  6  4 18  9 16 13]

[[ 2  4  7 10  4]
 [15  2  3 19  6]
 [ 4 18  9 16 13]]

[[ 2  4  7  0  4]
 [15  2  3  0  6]
 [ 4  0  9 16 13]]


In [ ]:
# Importing the Numpy Package
import numpy as np
# Now Creating a 2D array of size 4X3 which is composed of 4 byte integer elements
arr = np.array([[1,2,3,], [4,5,6], [7,8,9], [10,11,12]],np.int32)
# Printing the array
print(arr)

print()

# Printing the Shape of the created array
print("The Shape of the array is: ", arr.shape)

print()

# Printing the type of array
print("The Type of the Array is: ", type(arr))

print()

# Printing the data type of the array
print("The Data Type pf the array is:", arr.dtype)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

The Shape of the array is:  (4, 3)

The Type of the Array is:  <class 'numpy.ndarray'>

The Data Type pf the array is: int32


In [ ]:
# Importing the Numpy Package
import numpy as np
# Creating an array named "Random_Array"
Random_Array = np.array([[0,1,2], [3,4,5]])
print(Random_Array)
# Creating an another variable named "Diagonal_Add"
Diagonal_Add = np.trace(Random_Array)
# Here I used the trace method in order to calculate the sum of the diagonal elements in the given array.

# Printing the sum of diagonal elements
print("The sum of the diagonal elements of the given array is : ", Diagonal_Add)

[[0 1 2]
 [3 4 5]]
The sum of the diagonal elements of the given array is :  4


In [ ]:
# Importing the Numpy Package
import numpy as np
# Importing the nan function fromm numpy package
from numpy import nan
# Declaring an array
array1 = np.array([[4, 2, nan, 1], [11, 12, 14, 9], [5, nan, 1, nan]])
# Finding the missing data in the declared array
missing_data = np.isnan(array1)
# Here I am using the isnan() function to identify the missing elements in the declared array
# Printing the Boolena output of the missing data
print("The Missing Data is the declared variable is:\n", missing_data)

The Missing Data is the declared variable is:
 [[False False  True False]
 [False False False False]
 [False  True False  True]]


In [ ]:
# Importing the Numpy Package
import numpy as np
# Creating random array of Even Integers range from 10 to 70
even_array = np.arange(10,71,2)
print("Even Array is:\n", even_array)
# Creating random array of Odd Integers range from 10 to 70
odd_array = np.arange(11,71,2)
print("Even Array is:\n", odd_array)

# To perform at-least three element-wise mathematical operations using two arrays of the same size.
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print("Addition of two arrays = \n", arr1+arr2)
print("Subtraction of two arrays = \n", arr2-arr1)
print("Multiplication of two arrays = \n", arr1*arr2)


# Create the given array
arr = np.array([[5.54, 3.38, 7.99],
                  [3.54, 4.38, 6.99],
                  [1.54, 2.39, 9.29]])

# Sort the array by rows in ascending order
sorted_by_row = np.sort(arr, axis=1)

# Sort the array by columns in ascending order
sorted_by_column = np.sort(arr, axis=0)

print("Sorted by Row:")
print(sorted_by_row)
print("\nSorted by Column:")
print(sorted_by_column)

Even Array is:
 [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70]
Even Array is:
 [11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57
 59 61 63 65 67 69]
Addition of two arrays = 
 [ 6  8 10 12]
Subtraction of two arrays = 
 [4 4 4 4]
Multiplication of two arrays = 
 [ 5 12 21 32]
